### PR TITLE
Remove swap requirement

### PR DESCRIPTION
**Pull request by BDouze**
## Problem

- It is not possible to install on a server that does not have swap space even if there is plenty of RAM available.

## Solution

- Remove the checks on swap space

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by JimboJoe** [comment]
Thanks for your proposal. Having a swap is an [upstream requirement](https://github.com/discourse/discourse/blob/main/docs/INSTALL.md), so I think it's better to stick to that, so that Discourse support can be provided if needed (and to avoid what was [feared initially](https://meta.discourse.org/t/create-a-swapfile-for-your-linux-server/13880): random process termination during upgrade).

**Comment by zamentur** [comment]
On some VPS (using ZFS), it's not possible to create a swap file. I agree if there is a lot of ram we probably should ignore this requirement (upstream says swap file if needed with 1G ram).

**Comment by tio-trom** [comment]
Please either remove this or bring it down to 10. 50 for swapiness is a lot in my view. Even Discord recommends 10 https://meta.discourse.org/t/create-a-swapfile-for-your-linux-server/13880

I moved to a new server where I cannot modify the swapiness and it is 10. So I cannot restore my Discord...

**Comment by tio-trom** [comment]
How about doing it like this https://github.com/YunoHost-Apps/discourse_ynh/pull/161 ?

**Comment by Salamandar** [comment]
Closed in favor of #161

**Pull request closed without merging**
