### PR TITLE
V.2.5.4

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem
- *New version available*

## Solution
- *Update to upstream version 2.5.1*
- *Update Ruby to 2.7.1*
- *Update Ruby Build*
- *Upgrade ldap plugin*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/discourse_ynh%20PR61%20(ericgaspar)/)  

Add this is the output of package_check on my server...
```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      SUCCESS
Deleting from a sub path:        SUCCESS
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         SUCCESS
Installation in private mode:    SUCCESS
Installation in public mode:     SUCCESS
Multi-instance installations:    FAIL
Malformed path:                  Not evaluated.
Port already used:               Not evaluated.
Backup:                          SUCCESS
Restore:                         SUCCESS
Change URL:                      SUCCESS
Actions and config-panel:        Not evaluated.
```

### CODE REVIEW

**Comment by JimboJoe** [comment]
Hi, what was wrong with this PR... ?

**Comment by ericgaspar** [comment]
> Hi, what was wrong with this PR... ?

Hi, I wanted to know more about the fact that the jenkins CI completely fails the tests while on my server the tests pass (I am re-running now tests so I can share whats passing and failling on my CI)… maybe I could reopen the PR so someone can test it on is own machine?

**Comment by JimboJoe** [comment]
The multi-instance test usually fails on my dev server due to the lack of free memory.

**Comment by ericgaspar** [comment]
> The multi-instance test usually fails on my dev server due to the lack of free memory.

How much RAM does your dev server have? (mine has 8 GB ...)

**Comment by JimboJoe** [comment]
Small VM with 2GB RAM :wink:

**Comment by ericgaspar** [comment]
Made a small update and retry a test 💤
Still failling at the same place: Multi-instance -> sous.domain.tld/path

```
Multi-instance installations

Try to access by url...
Test url: sous.domain.tld/path
Real url: https://sous.domain.tld/path
HTTP code: 502
The HTTP code show an error.
Title of the page:
Extract of the page:
                               502 Bad Gateway
     __________________________________________________________________

                                    nginx


Test url: sous.domain.tld/path/
Real url: https://sous.domain.tld/path/
HTTP code: 502
The HTTP code show an error.
Title of the page:
Extract of the page:
                               502 Bad Gateway
     __________________________________________________________________

                                    nginx
```

**Comment by JimboJoe** [comment]
Hi,
I updated to 2.5.2 and fixed multi-instance mode by using a recent parameter (`UNICORN_LISTENER`) to set properly to socket communication (was priorly "patched" and here it was failing because it reverted to TCP port and it created a conflict on port 3000).
Can you have a try on your side please?

**Comment by ericgaspar** [comment]
Yeaa \o/
I got no failing on my server CI.

```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      SUCCESS
Deleting from a sub path:        SUCCESS
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         SUCCESS
Installation in private mode:    SUCCESS
Installation in public mode:     SUCCESS
Multi-instance installations:    SUCCESS
Malformed path:                  Not evaluated.
Port already used:               Not evaluated.
Backup:                          SUCCESS
Restore:                         SUCCESS
Change URL:                      SUCCESS
Actions and config-panel:        Not evaluated.
```

**Comment by ericgaspar** [comment]
@JimboJoe Shall we merge?

**Comment by JimboJoe** [comment]
I just tried an upgrade on my 2.3.10 version. It failed on ruby-build installation: https://paste.yunohost.org/raw/ubebelovok

**Comment by JimboJoe** [comment]
I upgraded to 2.5.4 and fixed an issue with older installations with outdated ruby-build plugin lacking ruby 2.7.0.
Should be OK now.
Wanna give it a last try, @ericgaspar ?

**Comment by ericgaspar** [comment]
@JimboJoe I finally manage to run the test to the end and it does not report any error.

**Comment by JimboJoe** [comment]
Then maybe it's TIIIME TO RELEAAASE?

**Pull request merged**
