### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/discourse_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Review by alexAubin — APPROVED** [review]

**Comment by alexAubin** [comment]
!testme

(though idk if the new CI is able to handle discourse)

**Comment by JimboJoe** [comment]
> (though idk if the new CI is able to handle discourse)

No, unfortunately no swap partition is detected... :disappointed_relieved:

**Comment by alexAubin** [comment]
@yalh76 @JimboJoe : sooo uuuh shall we yolomerge considering the app is level 0 anyway ?

**Comment by yalh76** [comment]
Just waiting for own CI results ^^

**Comment by yalh76** [comment]
# Own CI result for Revision: 72e8e077a1bad3471ddf41466bf02b4751c106df 

image

**Comment by alexAubin** [comment]
I'm clicking the button then

**Pull request merged**
