### PR TITLE
2.8.3

### PR DESCRIPTION
**Pull request by ericgaspar**
## Solution

- *Upgrade to 2.8.3*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by ericgaspar** [comment]
!testme

**Comment by weex** [comment]
Kind of strange that it says failure but all green OKs in the output. Seems a pretty straightforward update.

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
The patchs don't apply anymore :/

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request closed without merging**
