### PR TITLE
Merge master back into testing

### PR DESCRIPTION
**Pull request by decentral1se**
This just adds ab84df51e346407b329a2ec6dc39d4434d473d7f into the testing branch.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Hm... isn't that simpler and better to make a PR from master to testing...?

**Comment by decentral1se** [comment]
Yes, typically :)

But I couldn't install the application on testing without this patch.

This commit was only merged into the master branch?

**Comment by JimboJoe** [comment]
Yes, you made it directly on master in https://github.com/YunoHost-Apps/discourse_ynh/pull/27 :wink:

**Comment by decentral1se** [comment]
Yep, so can you merge this or? 

I just want this commit "backported" to testing so I can run installations from testing.

https://github.com/YunoHost-Apps/discourse_ynh/commits/testing ?

**Comment by JimboJoe** [comment]
Done by #36.

**Pull request closed without merging**
